"""The Tier 2 report and the gate-decision entry for DECISIONS.md. Spec §15.2; preregistration_tier2 §10.

Everything is generated from the stored evaluation series and run records, so
``make tier2`` (or ``--stage report``) reproduces it. The report states the
disclosure the pre-registration commits to, in its own words, so a reader of the
report alone is not misled about what the test split has already been used for.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from prism.agents.tier2 import BENCHMARKS, Tier2Plan, overfitting_table
from prism.analysis.tier2 import METRICS
from prism.reporting.report import md_table

__all__ = ["build_tier2_report", "decisions_entry", "append_decisions", "sanity_markdown", "DECISIONS_MARKER"]

DECISIONS_MARKER = "## Gate decisions (Tier 2)"
_NICE = {"annualised_return": "ann. return", "sharpe": "Sharpe", "max_drawdown": "max drawdown", "cvar_95": "CVaR 95%"}


def _f(x: float, nd: int = 3) -> str:
    return "n/a" if x is None or not np.isfinite(x) else f"{x:.{nd}f}"


def _pct(x: float, nd: int = 1) -> str:
    return "n/a" if x is None or not np.isfinite(x) else f"{100 * x:.{nd}f}%"


def _fmt(m: str, x: float) -> str:
    return _pct(x) if m in ("annualised_return", "max_drawdown", "cvar_95") else _f(x, 2)


def _git_head(root: Path) -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip()
    except Exception:  # noqa: BLE001
        return "unknown"


def _gate_lines(gates: dict[str, Any], key: str) -> list[str]:
    out = []
    for name, g in gates.items():
        p, n = g["paired"], g["non_overlap"]
        out.append(
            f"- **{name}: {'PASS' if p['pass'] else 'FAIL'}** (paired rule: favourable {p['favourable']}/{p['of']}, "
            f"adverse {p['adverse']}/{p['of']}); spec's non-overlapping-CI version: "
            f"{'pass' if n['pass'] else 'fail'} (favourable {n['favourable']}/{n['of']}, adverse {n['adverse']}/{n['of']})"
        )
    return out


def decisions_entry(plan: Tier2Plan, res: dict[str, Any], frozen: dict[str, Any], commit: str) -> str:
    g = res["gates"][plan.block]
    claims = res["claims"].set_index(["candidate", "control"])
    L = [DECISIONS_MARKER, ""]
    summary = " · ".join(f"{k}: {'PASS' if v['paired']['pass'] else 'FAIL'}" for k, v in g.items())
    L.append(f"### Gate decisions · {summary}")
    L.append(f"**Date:** {pd.Timestamp.now('UTC').date()} · **Phase B result, exploratory (D-032, preregistration_tier2 §0)** · "
             f"run under `reports/tables/preregistration_tier2.md`; code at commit `{commit}`; full tables in `reports/tier2_report.md`, "
             f"regenerated by `make tier2`. Evaluation window {res['first']} .. {res['last']} ({res['n_sessions']} sessions). "
             "The holdout was not read.")
    L.append("")
    L.append("Rule, as pre-registered: a comparison X vs Y passes iff the paired 95% CI (stationary block bootstrap, "
             f"block {plan.block}, {plan.n_bootstrap} replicates, shared day paths, seeds resampled within each variant) is favourable on at "
             "least 3 of the 4 primary metrics (annualised net return, net Sharpe, max drawdown, CVaR 95%) and adverse on none. "
             "Candidate statistic = mean over the variant's seeds of the metric.")
    L.append("")
    for name, v in g.items():
        t = res["paired"][plan.block]
        x, y = name.split(">")
        rows = t[(t.candidate == x) & (t.control == y)]
        parts = []
        for _, r in rows.iterrows():
            parts.append(f"`{r.metric}` {_fmt(r.metric, r['diff'])} [{_fmt(r.metric, r.ci_low)}, {_fmt(r.metric, r.ci_high)}] {r.verdict}")
        c = claims.loc[(x, y)]
        L.append(f"* **{x} vs {y}: {'PASS' if v['paired']['pass'] else 'FAIL'}** "
                 f"({v['paired']['favourable']}/4 favourable, {v['paired']['adverse']}/4 adverse); spec's non-overlap version: "
                 f"{'pass' if v['non_overlap']['pass'] else 'fail'} ({v['non_overlap']['favourable']}/4). "
                 f"Median DSR of {x} across seeds {_f(c.dsr_median_candidate, 2)} -> "
                 f"{'claimable' if c.claimable else 'not claimable (needs the gate AND DSR >= 0.95)'}. Differences: " + "; ".join(parts) + ".")
    L.append("")
    L.append("Block-length sensitivity (verdict of the paired rule): " + "; ".join(
        f"block {b}: " + ", ".join(f"{k} {'pass' if v['paired']['pass'] else 'fail'}" for k, v in gb.items())
        for b, gb in res["gates"].items() if b != plan.block) + ".")
    L.append("")
    L.append("**Limitations recorded with the decision.** (a) The evaluation split is the Tier 1 test split, already viewed in Tier 1 and "
             "used to choose the variant set (D-029, D-032); this result is exploratory, and confirmatory evidence needs the holdout "
             "under its own pre-registration (build step 5). (b) Hyperparameters were tuned on one validation year (about 46 weekly "
             "decisions), so selection is noisy. (c) One test window; per-episode numbers are descriptive. (d) Seeds share the data, so "
             "the seed band is optimiser variance, not sampling variance of the market.")
    L.append("")
    return "\n".join(L)


def append_decisions(root: Path, text: str, marker: str = DECISIONS_MARKER) -> bool:
    """Append once: returns False (and writes nothing) if an entry with ``marker`` is already present."""
    path = root / "DECISIONS.md"
    cur = path.read_text()
    if marker in cur:
        return False
    path.write_text(cur.rstrip("\n") + "\n\n---\n\n" + text.rstrip("\n") + "\n")
    return True


def build_tier2_report(plan: Tier2Plan, cfg, res: dict[str, Any], frozen: dict, sanity: dict, path: Path) -> Path:  # noqa: ANN001
    commit = _git_head(plan.root)
    tuning = pd.read_csv(plan.out_dir / "tuning_table.csv")
    over = overfitting_table(plan, frozen)
    meta = json.loads((plan.out_dir / "eval_done.json").read_text())
    L: list[str] = []
    A = L.append
    A("# PRISM — Tier 2 report (step 4c, Phase B)" + (" — SMOKE RUN, NOT A RESULT" if plan.smoke else ""))
    A("")
    A(f"Generated by `make tier2` at commit `{commit}`. Pre-registration: `reports/tables/preregistration_tier2.md`. "
      f"Evaluation split **{plan.eval_split}**, {res['first']} .. {res['last']}, {res['n_sessions']} sessions. "
      "Holdout not read.")
    if plan.smoke:
        A("")
        A("> **Smoke run.** Tiny budget, validation split in place of test, reduced grid and seeds. It exercises the pipeline; it is not a result.")
    A("")
    A("> **Disclosure.** The test split (2019-01-01 .. 2023-11-22) was viewed in Tier 1 (step 3 latent probe, Tier 1 probes and allocators) "
      "and the Phase B variant set (V1, V2, V4, C4) was chosen after that. This evaluation is therefore **exploratory**, not "
      "confirmatory. The holdout (2024-01-01 ..) is reserved for build step 5 under its own pre-registration.")
    A("")
    A("## 1. Gate decisions")
    A("")
    A(f"Paired rule, block {plan.block} (governs): a comparison passes iff favourable on >= 3 of 4 primary metrics and adverse on none.")
    A("")
    L.extend(_gate_lines(res["gates"][plan.block], "paired"))
    for b in plan.block_sensitivity:
        A("")
        A(f"Sensitivity, block {b}:")
        L.extend(_gate_lines(res["gates"][b], "paired"))
    A("")
    A("Every paired difference (candidate minus control; larger is better for all four metrics):")
    A("")
    t = res["paired"][plan.block].copy()
    t["difference [95% CI]"] = [f"{_fmt(r.metric, r['diff'])} [{_fmt(r.metric, r.ci_low)}, {_fmt(r.metric, r.ci_high)}]" for _, r in t.iterrows()]
    t["metric"] = t["metric"].map(_NICE)
    t["candidate seed-mean"] = [_fmt(m, v) for m, v in zip(res["paired"][plan.block].metric, t.x)]
    t["control seed-mean"] = [_fmt(m, v) for m, v in zip(res["paired"][plan.block].metric, t.y)]
    A(md_table(t[["candidate", "control", "metric", "candidate seed-mean", "control seed-mean", "difference [95% CI]", "verdict", "nonoverlap_verdict"]]))
    A("")
    A("`claimable` = the gate passes AND the candidate's median deflated Sharpe across seeds is >= 0.95:")
    A("")
    c = res["claims"].copy()
    c["dsr_median_candidate"] = c["dsr_median_candidate"].map(lambda x: _f(x, 2))
    A(md_table(c))
    A("")
    A("## 2. Sanity gates (train/validation only)")
    A("")
    A(f"Config {sanity['config']['cfg_id']}, reward scale {sanity['settings']['reward_scale']}. "
      f"**Degenerate task: {'PASS' if sanity['degenerate_task']['passed'] else 'FAIL'}; "
      f"beats random: {'PASS' if sanity['beats_random']['passed'] else 'FAIL'}.** See `reports/tables/tier2_sanity.md`.")
    A("")
    A("## 3. Seed distribution (final runs, headline cost, per-seed metrics)")
    A("")
    b = res["band"]
    rows = []
    for v in plan.variants:
        r = {"variant": v, "config": frozen[v].cfg_id}
        for m in ("annualised_return", "sharpe", "max_drawdown", "cvar_95"):
            x = b[(b.variant == v) & (b.metric == m)].iloc[0]
            r[_NICE[m]] = f"{_fmt(m, x['mean'])} ± {_fmt(m, x['std'])} (min {_fmt(m, x['min'])}, max {_fmt(m, x['max'])})"
        rows.append(r)
    A(md_table(pd.DataFrame(rows)))
    A("")
    A("## 4. Benchmarks, re-run through the environment (same cost model)")
    A("")
    bm = res["benchmarks"]
    ci = res["benchmark_ci"]
    rows = []
    for name in BENCHMARKS:
        r = {"benchmark": name}
        for m in METRICS:
            q = ci[(ci.benchmark == name) & (ci.metric == m)].iloc[0]
            r[_NICE[m]] = f"{_fmt(m, q.point)} [{_fmt(m, q.ci_low)}, {_fmt(m, q.ci_high)}]"
        rows.append(r)
    A(md_table(pd.DataFrame(rows)))
    A("")
    A("Benchmark turnover is per weekly step; costs and slippage as the agents (5 bps per side per risky leg + 0.02 x trailing daily vol). "
      "These numbers are not comparable with Tier 1's allocator table (a different cost convention, D-034).")
    A("")
    A("## 5. Deflated Sharpe")
    A("")
    A(f"Per-period Sharpe variance across the {len(plan.variants) * len(plan.final_seeds)} final strategies: {res['sharpe_variance']:.3e}. "
      f"SR0 at N={plan.dsr_trials_headline}: {res['sr0'][plan.dsr_trials_headline]:.5f}; at N={plan.dsr_trials_all_runs}: {res['sr0'][plan.dsr_trials_all_runs]:.5f}.")
    A("")
    d = res["dsr"].copy()
    A(md_table(d.round(3).fillna("")))
    A("")
    A("## 6. Drawdown episodes (SPY, >= 10%) and calendar years")
    A("")
    if res["episodes"].empty:
        A("No SPY drawdown of 10% or more in this window.")
    else:
        for e in res["episode_list"]:
            A(f"- peak {e['peak']}, trough {e['trough']}, recovery {e['recovery']}, depth {_pct(e['depth'])}")
        A("")
        ep = res["episodes"]
        rows = []
        for (i, s), g in ep.groupby(["episode", "strategy"], sort=False):
            g = g.iloc[0]
            rows.append({"episode": i, "strategy": s, "decline": _pct(g["decline_return_mean"]), "recovery": _pct(g["recovery_return_mean"]),
                         "max drawdown inside": _pct(g["max_drawdown_in_episode_mean"])})
        A(md_table(pd.DataFrame(rows)))
        A("")
        A("Variants show the mean over seeds; per-episode numbers are descriptive (a handful of episodes), no CI is claimed beyond section 1.")
    A("")
    cal = res["calendar"]
    A(md_table(cal.assign(annualised_return=cal.annualised_return.map(_pct), sharpe=cal.sharpe.map(lambda x: _f(x, 2)),
                          max_drawdown=cal.max_drawdown.map(_pct))))
    A("")
    A("## 7. Cost sensitivity (spec §11)")
    A("")
    cs = res["cost"]
    piv = cs.pivot(index="strategy", columns="bps", values="sharpe").round(2)
    A("Net Sharpe by cost level (bps per side; both cost terms scale):")
    A("")
    A(md_table(piv, index=True))
    A("")
    A("Mean one-way turnover per weekly step (seed mean for variants):")
    A("")
    A(md_table(res["turnover"].round(4)))
    A("")
    A("## 8. Overfitting: train vs validation, per seed")
    A("")
    A("Mean per-decision log net return of the deterministic policy over the whole train split and over the validation split, at the "
      "checkpoint selected on validation (and at the last checkpoint). The test split plays no part.")
    A("")
    o = over[["variant", "seed", "best_step", "train_at_best", "val_best", "gap_at_best", "train_final", "val_final", "gap_final"]].copy()
    for col in o.columns[3:]:
        o[col] = o[col].map(lambda x: f"{x:+.5f}")
    A(md_table(o))
    A("")
    ov = over.groupby("variant")[["train_at_best", "val_best", "gap_at_best", "train_final", "val_final", "gap_final"]].mean()
    A("Mean over seeds:")
    A("")
    A(md_table(ov.round(5), index=True))
    A("")
    A("## 9. Tuning (validation only)")
    A("")
    A("Mean over the tuning seeds of the best-checkpoint validation score; the winner per variant (first row of each variant) was frozen "
      "before any final run.")
    A("")
    A(md_table(tuning.round(5)))
    A("")
    A("## 10. Run record")
    A("")
    A(f"Steps per run {plan.steps}; checkpoint every {plan.eval_every}; reward scale {plan.settings.reward_scale}; "
      f"{plan.n_bootstrap} bootstrap replicates; master seed {plan.master_seed}; tuning seeds {list(plan.tuning_seeds)}; "
      f"final seeds {list(plan.final_seeds)}. Evaluation sessions {meta['first']} .. {meta['last']}.")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(L) + "\n")
    return path


# --------------------------------------------------------------------------- #
# the sanity-gate record
# --------------------------------------------------------------------------- #
SANITY_HISTORY = """\
## Attempt history

Recorded as run, in order. Exploratory runs used synthetic data only, and no real split other than train/validation.

| # | Change | Degenerate task | Beats random |
|---|---|---|---|
| 0 | baseline: reward scale 1, 20 000 steps, random 16-dim states, 95th-percentile bar, final checkpoint | fail: edge weight 0.26-0.35 of cap, 0.06-0.34 of oracle | fail: val -0.0005 to -0.0006 per decision; 95th pct of random +0.00001 |
| 1 | reward scale 100 (otherwise as 0) | fail: 0.44-0.58 of cap | fail: val -0.0018 to -0.0029; train +0.011 (heavily overfit) |
| - | exploratory, synthetic only: reward scale {10, 30, 100} x lr {3e-4, 1e-3}, 20 000 steps | all fail (0.39-0.66 of cap) | - |
| - | exploratory, synthetic only: scale {1, 10, 30} at 60 000 and 150 000 steps | **worse with more steps** (scale 1: 0.84 of cap at 60k, 0.79 at 150k; scale 10: 0.74 -> 0.43; scale 30: 0.58 -> 0.25) | - |
| design fix | gate 1: constant state (random features let the net memorise the one noise path: overfitting, not an optimiser fault), 3 000 sessions. One seed: scale 1 passes at 30k, **fails at 100k** (0.60 of cap), passes at 200k; scale 10 passes at 30k, 100k and 200k | | |
| design fix | gate 2: bar moves from the 95th percentile to the **median**; checkpoint from the final one to the validation-selected one. A constant equal-weight mix (-0.00059) sits below the 95th percentile of random policies (+0.00001) on 2018's validation window, so that bar measures the market, not the learner. Decided before the production-length run | | |
| 2 | reward scale 10, 300 000 steps, checkpoint every 10 000, both gates as redesigned | **pass** (0.92-1.00 of cap; 0.84-1.05 of oracle) | **pass** (selected-checkpoint ranks 0.93 / 0.82 / 0.88 among 200 random policies; none above the 95th percentile; final checkpoints rank 0.70 / 0.23 / 0.17) |
| 3 | the production budget: reward scale 10, **250 000 steps, checkpoint every 5 000** (re-run because the budget was reduced from 300 000 once the per-run time was measured, and the cadence refined because two of three selected checkpoints in attempt 2 were the first one) | **pass** (1.00 / 1.00 / 1.00 of cap; 0.98 / 0.83 / 0.92 of oracle) | **pass** (selected-checkpoint ranks 0.93 / 0.82 / 0.92 at steps 190 000 / 10 000 / 15 000; none above the 95th percentile; final checkpoints rank 0.75 / 0.40 / 0.68). **The record the pipeline checks.** |

Learning rate and observation normalisation were not needed. Reward scale 10 was chosen from the synthetic-gate exploration, before the production-length run.
"""


def sanity_markdown(rec: dict[str, Any]) -> str:
    d, b = rec["degenerate_task"], rec["beats_random"]
    L = ["# Tier 2 sanity gates (build step 4c)", ""]
    L.append(f"Train and validation only; no test-split row is read. Config `{rec['config']['cfg_id']}`, reward scale "
             f"{rec['settings']['reward_scale']}, **{rec['steps']} steps**, checkpoint every {rec.get('eval_every', '?')} steps, "
             f"seeds {[s['seed'] for s in d['seeds']]}. Written by `scripts/05_train_agents.py --stage sanity` "
             f"(`data/processed/tier2/sanity.json`). **Overall: {'PASS' if rec['passed'] else 'FAIL'}.**")
    L += ["", f"## 1. Degenerate task: {'PASS' if d['passed'] else 'FAIL'}", "",
          "One asset (XLK) with a constant +0.2% daily return, the other twelve zero-mean noise, constant state, real cost model. "
          "Pass: every seed holds XLK at >= 0.85 of the 0.35 cap and earns >= 0.75 of the oracle's log return, on a fresh noise path.", ""]
    rows = [{"seed": s["seed"], "mean XLK weight": round(s["edge_weight_mean"], 4), "of cap": round(s["edge_weight_fraction_of_cap"], 3),
             "agent log return/step": round(s["agent_mean_log_return"], 5), "oracle": round(s["oracle_mean_log_return"], 5),
             "of oracle": round(s["log_return_fraction_of_oracle"], 3), "wall s": round(s["wall_seconds"]), "pass": s["passed"]} for s in d["seeds"]]
    L.append(md_table(pd.DataFrame(rows)))
    L += ["", f"## 2. Beats random on validation: {'PASS' if b['passed'] else 'FAIL'}", "",
          f"V1, real train split, validation-selected checkpoint, against 200 i.i.d.-uniform-action random policies on the real validation "
          f"split (median {_f(b['random_median'], 5)}, max {_f(b['random_max'], 5)}, 95th percentile {_f(b['reported_threshold_mean_log_return'], 5)}). "
          f"Gate: the selected checkpoint beats the median in >= 2 of 3 seeds. A constant equal-weight mix scores "
          f"{_f(b['equal_weight_constant_policy_val'], 5)}, rank {_f(b['equal_weight_constant_percentile_rank'], 2)} among the random policies.", ""]
    rows = []
    for s in b["seeds"]:
        rows.append({"seed": s["seed"], "selected step": s["selected"]["step"],
                     "selected val": round(s["selected"]["val"]["mean_log_return"], 5), "rank": round(s["selected_percentile_rank"], 3),
                     "above median": s["beats_gate_quantile"], "above 95th": s["selected_beats_reported_quantile"],
                     "selected train": round(s["selected"]["train"]["mean_log_return"], 5),
                     "final val": round(s["final"]["val"]["mean_log_return"], 5), "final rank": round(s["final_percentile_rank"], 3),
                     "final train": round(s["final"]["train"]["mean_log_return"], 5)})
    L.append(md_table(pd.DataFrame(rows)))
    L += ["", "Reading (not gating): the final checkpoints fit the train split far better than they predict validation (train mean log return "
          "about +0.02 per decision against about -0.001 to -0.002); the validation-selected checkpoint is often an early one. That overfitting "
          "is the main risk to the Tier 2 result, and the overfitting report measures it for every final run.", "", SANITY_HISTORY]
    return "\n".join(L)
